"""
PowerPoint generator. Converts Claude's markdown briefing into a consultative deck.

Parsing strategy:
- ## Headers -> new slide
- Bullet lists -> slide bullets
- [p.X] citations -> footer note
- **bold** -> bold text
"""
import re
from io import BytesIO
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

ACCENT = RGBColor(0x18, 0x5F, 0xA5)
DARK = RGBColor(0x2C, 0x2C, 0x2A)
GRAY = RGBColor(0x5F, 0x5E, 0x5A)
LIGHT_GRAY = RGBColor(0xD3, 0xD1, 0xC7)


def _parse_briefing(text: str) -> list[dict]:
    """
    Parse markdown briefing into slide structure.
    Returns: [{"title": str, "bullets": [str], "raw": str}]
    """
    sections: list[dict] = []
    current: dict | None = None

    for line in text.split("\n"):
        if line.startswith("## "):
            if current:
                sections.append(current)
            current = {
                "title": line.removeprefix("## ").strip(),
                "bullets": [],
                "raw": "",
            }
        elif current is not None:
            current["raw"] += line + "\n"
            stripped = line.strip()
            if stripped.startswith(("- ", "* ", "• ")):
                bullet_text = re.sub(r"^[-*•]\s+", "", stripped)
                current["bullets"].append(bullet_text)
            elif re.match(r"^\d+\.\s+", stripped):
                bullet_text = re.sub(r"^\d+\.\s+", "", stripped)
                current["bullets"].append(bullet_text)

    if current:
        sections.append(current)

    return sections


def _add_title_slide(prs: Presentation, title: str, subtitle: str):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    tx_box = slide.shapes.add_textbox(Inches(0.7), Inches(2.5), Inches(11.6), Inches(1.5))
    tf = tx_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.color.rgb = DARK

    sub_box = slide.shapes.add_textbox(Inches(0.7), Inches(4.2), Inches(11.6), Inches(0.8))
    sub_p = sub_box.text_frame.paragraphs[0]
    sub_p.text = subtitle
    sub_p.font.size = Pt(16)
    sub_p.font.color.rgb = GRAY

    strip = slide.shapes.add_textbox(Inches(0.7), Inches(6.8), Inches(11.6), Inches(0.4))
    sp = strip.text_frame.paragraphs[0]
    sp.text = "Generated by ResearchPilot"
    sp.font.size = Pt(10)
    sp.font.color.rgb = LIGHT_GRAY


def _add_content_slide(prs: Presentation, section: dict):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(12.3), Inches(0.7))
    title_p = title_box.text_frame.paragraphs[0]
    title_p.text = section["title"]
    title_p.font.size = Pt(24)
    title_p.font.bold = True
    title_p.font.color.rgb = ACCENT

    body_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.4), Inches(11.9), Inches(5.5))
    body_tf = body_box.text_frame
    body_tf.word_wrap = True

    if section["bullets"]:
        for i, bullet in enumerate(section["bullets"][:8]):
            p = body_tf.paragraphs[0] if i == 0 else body_tf.add_paragraph()
            p.text = "• " + bullet
            p.font.size = Pt(14)
            p.font.color.rgb = DARK
            p.space_after = Pt(8)
    else:
        paragraphs = [p.strip() for p in section["raw"].split("\n\n") if p.strip()]
        for i, para in enumerate(paragraphs[:5]):
            p = body_tf.paragraphs[0] if i == 0 else body_tf.add_paragraph()
            p.text = para[:500]
            p.font.size = Pt(13)
            p.font.color.rgb = DARK
            p.space_after = Pt(10)


def _add_metadata_slide(prs: Presentation, metadata: dict, page_count: int, source_url: str):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(12.3), Inches(0.7))
    tp = title_box.text_frame.paragraphs[0]
    tp.text = "Company snapshot"
    tp.font.size = Pt(24)
    tp.font.bold = True
    tp.font.color.rgb = ACCENT

    fields = [
        ("Company", metadata.get("company_name", "—")),
        ("Ticker", metadata.get("ticker") or "—"),
        ("Fiscal year", metadata.get("fiscal_year", "—")),
        ("Reporting period end", metadata.get("reporting_period_end") or "—"),
        ("Currency", metadata.get("currency", "—")),
        ("Country (HQ)", metadata.get("country_hq", "—")),
        ("Industry", metadata.get("industry", "—")),
        ("Auditor", metadata.get("auditor") or "—"),
        ("Report type", metadata.get("report_type", "—")),
        ("Pages analyzed", str(page_count)),
    ]

    box = slide.shapes.add_textbox(Inches(0.7), Inches(1.5), Inches(11.9), Inches(5.0))
    tf = box.text_frame
    tf.word_wrap = True

    for i, (label, value) in enumerate(fields):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = f"{label}: {value}"
        p.font.size = Pt(14)
        p.font.color.rgb = DARK
        p.space_after = Pt(6)

    footer = slide.shapes.add_textbox(Inches(0.5), Inches(6.9), Inches(12.3), Inches(0.3))
    fp = footer.text_frame.paragraphs[0]
    fp.text = f"Source: {source_url[:120]}"
    fp.font.size = Pt(9)
    fp.font.color.rgb = GRAY


def generate_pptx(result: dict) -> bytes:
    """
    Generate a .pptx file from workflow output.
    Input: dict from AnnualReportResult.to_dict() or any workflow returning 'analysis' key.
    Output: bytes
    """
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    metadata = result.get("company_metadata", {}) or {}
    company_name = metadata.get("company_name") or "Research Briefing"
    fiscal_year = metadata.get("fiscal_year", "")

    _add_title_slide(
        prs,
        title=f"{company_name} — Executive Briefing",
        subtitle=f"{fiscal_year} Annual Report Analysis" if fiscal_year else "Analysis",
    )

    if metadata:
        _add_metadata_slide(
            prs,
            metadata=metadata,
            page_count=result.get("page_count", 0),
            source_url=result.get("source_url", "—"),
        )

    briefing_text = result.get("executive_briefing") or result.get("analysis", "")
    sections = _parse_briefing(briefing_text)
    for section in sections:
        _add_content_slide(prs, section)

    output = BytesIO()
    prs.save(output)
    return output.getvalue()
